logging:
  level:
    root: warn
    com.rest.api: info
    org.springframework.web: debug
    guru.springframework.controllers: info
    org.hibernate: error
    org.hibernate.SQL: debug

#  path: /home/ec2-user/api/log
#  file:
#    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studyroom?useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: studyroom
    password: test
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      generate-ddl: false
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none
  url:
    base: https://localhost:443